### ISSUE TITLE
An error occurred in the mac environment

### ISSUE THREAD

**Issue by King-Mr** [projectdiscovery/nuclei-burp-plugin#103]
current environment：
burp:20201201
nuclei-burp-plugin:1.1.3
nuclei:last version
<img width="1258" alt="image" src="https://github.com/projectdiscovery/nuclei-burp-plugin/assets/52808596/a92d8c7b-3484-4c52-ba44-a666c31f9596">

**Comment by forgedhallpass** [comment]
@King-Mr please make sure the nuclei path is configured correctly. You can check out the relevant section of the demo video at https://www.youtube.com/watch?v=PMHCnaU7dfo&t=117s

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue persists.
