### ISSUE TITLE
java8

### ISSUE THREAD

**Issue by riyuexc** [projectdiscovery/nuclei-burp-plugin#116]
希望能支持java1.8

**Comment by GeorginaReeder** [comment]
Hi there!

Closing this topic as it's not an issue with reproduceable steps.

**Comment by forgedhallpass** [comment]
@riyuexc Java 8 has reached end of life years ago and will not be supported. The minimum Java version for this plugin is Java 11, as mentioned in the [README](https://github.com/projectdiscovery/nuclei-burp-plugin/tree/main?tab=readme-ov-file#building-the-code). If I do remember correctly Burp Suite also requires at least Java 11 for extension development.
