### ISSUE TITLE
"The process exited with code -1" issue

### ISSUE THREAD

**Issue by soupnatzi** [projectdiscovery/nuclei-burp-plugin#24]
Was working perfect before but now when i create a template it throws this error was wondering if anyone else is facing this issue or faced this issue?

"The process exited with code -1"

**Comment by forgedhallpass** [comment]
Hello @soupnatzi,

Could you please provide more details like:
* are you using the pre-built JAR or have you built yourself the latest version?
* have you made sure the nuclei path is correct in the settings panel?
* have you tried executing the generated command line value in your terminal to see if it works?

**Comment by soupnatzi** [comment]
hey @forgedhallpass yea am using the pre-built JAR and everything else is fine and nuclei is working fine as am using my own templates too but for some reason now its throwing that error.

**Comment by forgedhallpass** [comment]
Do you happen to have anything in the logs (Burp Extender/Nuclei/Errors)?

Feel free to DM me on Discord: https://discord.gg/projectdiscovery

**Comment by soupnatzi** [comment]
i have nothing in the logs i am going to build it my self without using the pre build jar and see if that works.

**Comment by soupnatzi** [comment]
after building it its working now no idea what happen there but thanks for the quick response @forgedhallpass

**Comment by forgedhallpass** [comment]
Glad it worked, and now you can also enjoy some of the new features that will be only released with v1.1 ;)

I will try to also add more logging in the future.
