### ISSUE TITLE
On Windows the path is not correctly updated after saving

### ISSUE THREAD

**Issue by LuoooB** [projectdiscovery/nuclei-burp-plugin#40]
after save:
![image](https://user-images.githubusercontent.com/40429942/186101647-12487bb3-dee4-4150-89ab-9af5faec14c2.png)

**Comment by LuoooB** [comment]
how to fix it ?

**Comment by forgedhallpass** [comment]
Could you try using forward slashes in the settings e.g. `C:/Users/user/nuclei-templates` instead of `C:\Users\user\nuclei-templates`?

**Comment by forgedhallpass** [comment]
Update: I have actually implemented a fix in the associated PR, could you maybe give it a try to confirm it works as expected?

**Comment by LuoooB** [comment]
Bug still exists

> 更新：我实际上已经在相关 PR 中实施了一个修复程序，您可以尝试确认它按预期工作吗？

Bug still exists
![image](https://user-images.githubusercontent.com/40429942/200524789-f9ea5a6e-54bc-4058-9485-f812d34cb792.png)
