### ISSUE TITLE
path err when i save my template

### ISSUE THREAD

**Issue by LuoooB** [projectdiscovery/nuclei-burp-plugin#81]
![image](https://github.com/projectdiscovery/nuclei-burp-plugin/assets/40429942/c3152991-033f-401a-b532-a6303251b83e)

**Comment by forgedhallpass** [comment]
@LuoooB this has been fixed, but might not have been officially released.
Please try building the latest version of the code and use that.

It should be duplicate of: #40

**Comment by dogancanbakir** [comment]
Closing this. As stated by @forgedhallpass, this is a duplicate of #40.
