### ISSUE TITLE
Cannot be used with burpsuite2024.1 version

### ISSUE THREAD

**Issue by wt2266232** [projectdiscovery/nuclei-burp-plugin#96]
It used to be available on the version released by burp in January, but it suddenly became unavailable in the past few days.
<img width="516" alt="image" src="https://github.com/projectdiscovery/nuclei-burp-plugin/assets/75193672/7579c412-6eb0-45f1-93e6-c4f75879e7e5">
<img width="678" alt="image" src="https://github.com/projectdiscovery/nuclei-burp-plugin/assets/75193672/7b902823-40b2-48b3-8dca-847796bb1457">

**Comment by GeorginaReeder** [comment]
Thanks so much for bringing this to our attention @wt2266232 , we'll look into it!
